### ISSUE TITLE
Allow all projects to add additional subdistricts, not just School Choice projects

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#218]
If a user adds a subdistrict, then changes the BBL to a non-school choice zone, user loses the ability to remove the custom subdistrict.

**Comment by godfreyyeung** [comment]
@pichot Taking a stab at it... Does "add a subdistrict" refer to when a user selects from the list of subdistricts under "With Action Additional Schools"? (screenshot below) 
<img width="525" alt="Screen Shot 2019-05-29 at 5 18 12 PM" src="https://user-images.githubusercontent.com/3311663/58592235-024daa80-8236-11e9-9299-80850be63235.png">

Also, is there an example non-school choice zone BBL, or how do I find one? (I'm currently not confident I can correctly determine one)

**Comment by pichot** [comment]
Currently, a user can only add additional subdistricts if the project is in a 'School Choice' zone. I think the easiest, move intuitive path forward is to allow all projects to add additional subdistricts, not just School Choice projects. School Choice will continue to be indicated by the orange (!) on the Study Area tab.
