### ISSUE TITLE
Implement Ember Mirage for E2E testing & development sandbox

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/ceqr-app#250]
Current the ember app hits the development environment Rails API directly, in sandbox mode. In testing mode, there are no tests that require the API, so this is less of an issue.

We should install Ember Mirage so that we only need to simulate network responses in order to run tests and sandbox. This allows us to create very specific data scenarios and test those without the necessary overhead of creating this from the backend (something we would be doing anyways).

**Comment by allthesignals** [comment]
One alternative to this is [PollyJS](https://github.com/Netflix/pollyjs), which might work well for CEQR app. One big caveat is that it doesn't handle unusual file types very well (such as protobuf).

**Comment by pichot** [comment]
Why is wafflebot still touching these issues?
