### ISSUE TITLE
Create new model to hold "data packages"

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#257]
For every given analysis model, there can be any number of versions of data sets on which analysis can be run. 

The model(s) here could be a type of "data package": a collection / mapping of database table names, versioning data, and other information associated with a given 'cut' of CEQR data. The model could have a loosely-defined, analysis-specific schema for this collection / mapping, which provides pointers to tables in a read-only database.

This issue is closed when the front-end no longer stores this information, and, instead, it's handled through model relationships served from the backend.

**Comment by allthesignals** [comment]
Downstream of this, the front end will need to fetch this data from the back end which will require new model relationships. Instead of finding these data packages from the `public` folder, which still uses the `store` as an interface, it'll probably need to use an async relationship.
