### ISSUE TITLE
Transform CTPP spreadsheet into PFF schema

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#274]
- [x] Generate `ctpp_journey_to_work.2006_2010` with schema of:
  - residential_geoid
  - work_geoid
  - variable (`MODE`)
  - count
  - standard_error  

- [x] Generate `ctpp_censustract_lookup.2006_2010`
(Include all census tracts that exist in `ctpp_table_2006_2010`)
  - centroid
  - geoid

**Comment by pichot** [comment]
## Table for `MODE` conversion:

1 Total
2 Car, truck, or van -- Drove alone
3 Car, truck, or van -- In a 2-person carpool
4 Car, truck, or van -- In a 3-person carpool
5 Car, truck, or van -- In a 4-person carpool
6 Car, truck, or van -- In a 5-or-6-person carpool
7 Car, truck, or van -- In a 7-or-more-person carpool
8 Bus or trolley bus
9 Streetcar or trolley car
10 Subway or elevated
11 Railroad
12 Ferryboat
13 Bicycle
14 Walked
15 Taxicab
16 Motorcycle
17 Other method
18 Worked at home

**Comment by AmandaDoyle** [comment]
@pichot where is the raw CTPP data?

**Comment by pichot** [comment]
@AmandaDoyle https://www.dropbox.com/s/uwbkfsrwfqiw6rm/31CR%20to%2031CR.xlsx?dl=0

**Comment by baolingz** [comment]
@pichot Should we keep all US census tracts to do this projects? or we can eliminate some states?

**Comment by allthesignals** [comment]
@baolingz any updates on this? Thanks
