### ISSUE TITLE
Separate frontend and backend sections of the app

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#275]
This includes:

- setting up deployment of the frontend ember app to netlify
- networking frontend to backend
- backend will still deploy to heroku
- separating the folders as `backend` and `frontend`

**Comment by allthesignals** [comment]
Having Heroku deploy subdirectories seems messy: https://coderwall.com/p/ssxp5q/heroku-deployment-without-the-app-being-at-the-repo-root-in-a-subfolder

A less-invasive alternative is to simply develop from the frontend folder but don't serve the frontend via the Heroku deployment. Instead, the frontend can be served from Netlify, which allows you to specify your build command. This frontend can then consume the API deployed to Heroku.

This will obviously require CORS configuration, but that should be nbd.

**Comment by julialucyhogan** [comment]
sounds good ! @allthesignals  ty  for the research
