### ISSUE TITLE
Add Journey to Work selection column to TransportationAnalysis model

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#276]

**Comment by allthesignals** [comment]
This seems like a database migration exercise with some possible array parsing for the json-api-resources layer. It could be called `selection`. Looking at #279, it will infer intersecting Census tracts from the related project model.

**Comment by pichot** [comment]
JSON API resources handle arrays very well, so likely no need to write any additional parsing, just have to add the Rails model attribute to the corresponding JSON API resource for it to be readable/writable through the API.

**Comment by pichot** [comment]
I also would consider a more specific column name than `selection`, as the `TransportationAnalysis` model will likely store lots of other user "selections" as we add additional features.

Perhaps `jtw_study_selection` (jtw standing for Journey To Work)
