### ISSUE TITLE
Implement selection functionality to store census tracts in TransportationAnalysis model

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#279]
- Default state: select census tracts that intersect with the Project model's project area (`bbls_geom`). These census tracts cannot be unselected.
- User can add any other census tracts to study area
- Save/remove census tract geoid in TransportationAnalysis model on select/unselect
- Recalculate geographic centroid of study area on select/unselect and save it to the TransportationAnalysis model

**Comment by allthesignals** [comment]
> Default state: select census tracts that intersect with the Project model's project area (bbls_geom). These census tracts cannot be unselected.

Could be an after_save hook, as you were suggesting earlier...

> Save/remove census tract geoid in TransportationAnalysis model on select/unselect
I'm confused by the language here but I think this just means that the census tract geoids get updated when the user selects more census tracts for the study area.

**Comment by allthesignals** [comment]
> Recalculate geographic centroid of study area on select/unselect and save it to the TransportationAnalysis model

Hmm this could be done in memory? A simple method? Does it need to be saved to the database if it's computed from something else? J/w.

> User can add any other census tracts to study area

This is just setting new arrays on the `jtw_study_selection`, yes?

**Comment by allthesignals** [comment]
This is going to depend on some coordinate from #282. I could stub in some methods but I'm not sure the logic makes sense.

**Comment by julialucyhogan** [comment]
Still need to implement frontend portion of this work; now that map exists with census tract layer we can add click functionality to mutate the transportation model analysis via the UI
