### ISSUE TITLE
Create NYC census tract ACS attribute table on ceqr data with associated rails model

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#282]
ACS variables should come from the latest ACS 5-year estimate (in this case, 2017)

Schema should be:

- geoid (https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html)
- ACS variable: TOTAL POPULATION [B01003]
  - total_population
  - total_population_moe
- MEANS OF TRANSPORTATION TO WORK [B08301]
  - [all mode counts and moes]

**Comment by allthesignals** [comment]
@pichot to upload the real data
@allthesignals to impl the class, assuming: 1) geoid and 2) a polygon
