### ISSUE TITLE
Create Ember data representation of DB model for modal splits

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/ceqr-app#326]
Ember needs to be able to fetch data for the hover table and for the census tract selection 
 - Population
 - Modal splits (counts & percents)

For modal splits, currently only implement these variables:
 - trans_total
 - trans_auto_total
 - trans_public_total

Which represent the total number of people commuting from this tract, the number by auto, and the number by public transportation, respectively.

Flows from #281 as a separate issue

**Comment by pichot** [comment]
Table is now on `ceqr_data` database: `nyc_acs.2017`

With schema:
```sql
CREATE TABLE nyc_acs."2017" (
    geoid text,
    value integer,
    moe integer,
    variable text
);
```
`geoid` is census tract geoid
`variable` can be one of:

```
trans_total
trans_home
trans_auto_2
trans_walk
trans_public_subway
trans_auto_total
population
trans_public_ferry
trans_taxi
trans_auto_7_or_more
trans_motorcycle
trans_bicycle
trans_public_rail
trans_public_streetcar
trans_public_bus
trans_auto_solo
trans_auto_carpool_total
trans_other
trans_auto_4
trans_public_total
trans_auto_3
trans_auto_5_or_6
```
