### ISSUE TITLE
Create Unit Test for Solid Waste Analysis Model

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/ceqr-app#340]

**Comment by pichot** [comment]
@trbmcginnis we should actually remove Solid Waste Analysis model from the app entirely. It's a fragment from a development push I had started, but we've since pivoted to focus on other chapters. We won't be working on Solid Waste for a long time. See #343.

**Comment by pichot** [comment]
We should close this in favor of #343

**Comment by pichot** [comment]
Closing in favor of #343
