### ISSUE TITLE
Add additional layers to the map

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#379]
Add two layers to the map, both should be toggled off by default. The toggle should be similar to those found on Public Schools:

![Cursor_and_M_Crown__Public_Schools_.jpg](https://images.zenhubusercontent.com/5c9e3b7e0ad2b309f407982b/e58d66dc-b2c7-4f77-b957-797bab32b4da)

The layers are:

- [ ] Transit Zones (https://nycplanning-web.carto.com/u/planninglabs/tables/ceqr_transportation_zones_v2015/map)
- [ ] Land Use Colors (on Carto, query should be `SELECT * FROM mappluto`)
  - Style should be similar to Zola/Community Profiles. 

Land use colors:

![NYC_Planning___Community_Profiles.jpg](https://images.zenhubusercontent.com/5c9e3b7e0ad2b309f407982b/5a3eaab8-245b-4fe3-b1d2-d751f8cc64ef)

**Comment by julialucyhogan** [comment]
@pichot how should transit zones be visualized? is there a standard way EARD is used to seeing them? would rather not introduce other hovers, so hoping to capture this in fill color + map legend. For now will just make a random call but input required for final pass :)

**Comment by pichot** [comment]
@pichot use Import API to copy simplified Traffic Zones into Carto from CEQR Data.

**Comment by pichot** [comment]
@julialucyhogan simplified Traffic Zones are now on Carto at `ceqr_data_traffic_zones_2019`
