### ISSUE TITLE
As a user, I can see tables modal split and vehicle occupancy for JTW/RJTW

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#397]
As a user, I can see the complete modal splits for Journey to Work and Reverse Journey to Work.

- Journey to Work modal splits come from the latest ACS data.
- Reverse Journey to Work modal splits come from CTPP data.

Tables should look like this:
![Census Tract table.jpg](https://images.zenhubusercontent.com/5c9e3b7e0ad2b309f407982b/5b7e2f92-d028-4df2-b5f1-f4b96a81a28b)

Margins of Error should be shown alongside all counts as indicated in the mockup. To aggregate an MOE:

- Add together the square of all values
- Find the square root of this sum of squares

In js, something like:
```js
const squares = valuesArray.map((a => Math.pow(a, 2));
const sumOfSquares = squares.reduce((a, b) => a + b, 0);
Math.sqrt(sumOfSquares);
```

A user should also see the *Vehicle Occupancy* rate per census tract and the entire study area below the totals. This can be calculated by:
- Taking the total mode split of automobiles and weighting for automobile trips. To do this, divide the total count of people by the number of people in the car using the breakdown below:
  - 1 = Car, truck, or van -- Drove alone
  - 2 = Car, truck, or van -- In a 2-person carpool
  - 3 = Car, truck, or van -- In a 3-person carpool
  - 4 = Car, truck, or van -- In a 4-person carpool
  - 5.5 = Car, truck, or van -- In a 5-or-6-person carpool
  - 7 = Car, truck, or van -- In a 7-or-more-person carpool
- Sum these numbers and divide the total number of car trips.

**Comment by godfreyyeung** [comment]
@pichot will this table (with ability to switch between jtw and rjtw) be displayed on both the census tracts and trip generation step? 
If so, will it be the same or will it vary by step?

**Comment by pichot** [comment]
This is only on Census Tracts.

**Comment by godfreyyeung** [comment]
@pichot Do we have a formula for the "Total (work from home)" aggregate row? Sorry didn't think about this before.
For "Total (census)" I'm guessing it's just the aggregate of all the modes.

**Comment by godfreyyeung** [comment]
Deleted previous question as I found some info in this ticket: https://app.zenhub.com/workspaces/ceqr-app-5c9e3ba50ad2b309f4079836/issues/nycplanning/ceqr-app/370
