### ISSUE TITLE
Update Public Schools data to use 2019 datasets

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/ceqr-app#484]
Update 2019 data for public schools.

Once the 2017 and 2018 public schools data packages, and the application code has been adapted to the new changes coming from EDMs data pipeline, adding the 2019 public schools data should just require adding a new `db/seed.rb ` object.  Note for the seed to be added as a row in the rails database, `rails db:seed` must be manually run on the database (whether you're testing locally, on staging, or in production).

**Comment by bfreeds** [comment]
Related to:  #626 #625

**Comment by bfreeds** [comment]
Depends on (before deploy to production):
- https://github.com/NYCPlanning/ceqr-app-data/issues/46
- https://github.com/NYCPlanning/ceqr-app-data/issues/57

**Comment by bfreeds** [comment]
QA Feedback / Bug Fixes before Ready to Deploy to production, from @mshapiro1:
- [ ] Schools don't display on the CEQR App Map
- [ ] When adding additional subdistricts to the analysis in the "Study Area" section, the analysis doesn't actually integrate additional information from that subdistrict, and the map doesn't update.
- [ ] In the existing conditions scenario, the data source link on the bottom needs to be dated 2018-2019 
- [ ] In the map, there is an option to check a box to show school zones. This button does not work.
- [ ] The multipliers are out of date. The new data package doesn't provide the option to use the new SCA multipliers.
- [ ] No multiplier, existing conditions, or no-action scenario data updates when toggling between data packages.
- [ ] In the no-action scenario, both source data links should be dated 2019-2028. They link the right source though!
- [ ] Both links in the "SCA Schools Under Construction" section should be removed and replaced with this link, titled "SCA Capacity Projects in Process": http://www.nycsca.org/Community/Capital-Plan-Reports-Data#Local-Law-167-Reports-352
- [ ] In the no-action scenario, the option to add "Additional Residential Development" doesn't work. I can add a development, but it isn't integrated into the analysis numbers.
