### ISSUE TITLE
Add Next button at the bottom of all forms

### ISSUE THREAD

**Issue by kchanba** [NYCPlanning/ceqr-app#490]
End of Analysis Threshold page, Planning Factors and Trip Results

**Comment by pichot** [comment]
Where should the Next button go when on Trip Results?

Also, what should the Next button do if you have more than one Land Use? Should it go to the next Land Use, or should it go to Trip Results?

**Comment by kchanba** [comment]
I think the next button should change to a 'Save' on trip results. 

Maybe there can be a secondary button at the end of Trip Results next to 'Save' that would move you on to the next land use. let me mock something up.

**Comment by kchanba** [comment]
Maybe something like 
![image](https://user-images.githubusercontent.com/2378745/69380766-2e943200-0c81-11ea-9e90-2d91af9bda5b.png)

@pichot
