### ISSUE TITLE
Update styling of sticky transportation menu bar

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/ceqr-app#519]
Update styling for transportation factors & save/next nav bar (look at PR [#518](https://github.com/NYCPlanning/ceqr-app/pull/518))

- update styling of menu bar to be the entire width of the screen
- make it so that shadow only appears when a user has started scrolling
- make Save and Next button smaller

**Comment by allthesignals** [comment]
@trbmcginnis is this closed by your PR? Please re-open if not.
