### ISSUE TITLE
Add fragments to transportation-planning-factor model

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/ceqr-app#548]
Install `ember-data-model-fragments` and create fragments for `inOutSplits`, `truckInOutSplits`, `modeSplitsFromUser`, `vehicleOccupancyFromUser`. These fragments will make it easier to access these nested objects in the model and therefore enable our use of `model.hasDirtyAttributes`

**Comment by allthesignals** [comment]
We are going to move on from this approach until we do some more research. ember-m3 is a possibility.
