### ISSUE TITLE
Increase code coverage to 60%, with focus on transportation

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/ceqr-app#557]
Test divying: https://docs.google.com/spreadsheets/d/1_uGqds_QrLkj-sikmtAbMPUq6L4nnGgDcCP-HGuNRm0/edit?usp=sharing

**Comment by trbmcginnis** [comment]
Reached beyond 60%!

**Comment by allthesignals** [comment]
Great @trbmcginnis! Yay!
