### ISSUE TITLE
Decrease width of land use toggle when only one is selected

### ISSUE THREAD

**Issue by kchanba** [NYCPlanning/ceqr-app#576]
Right now, the toggle button still takes up the amount of space for two selections. Reduce to just the size of one if there are not two land uses.

![image.png](https://images.zenhubusercontent.com/589c977151aa2c305773ecdd/df9b0730-7029-47c6-a58a-91138708f8de)

Should look more like:

![image](https://user-images.githubusercontent.com/2378745/72542226-ca8d8480-3851-11ea-8b36-d0f225e0cdcc.png)

**Comment by allthesignals** [comment]
Closed bc the design haschanged
