### ISSUE TITLE
Project Creation Hangs with spinning wheel

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#614]
First reported by Kasia from external user, replicated by Kasia on her machine, and experienced during walkthrough by @kchanba.

When creating a project, users sometimes experience a hanging spinner where the project creation does not finish.  

Here's a screenshot of the console error experienced during walkthrough:
<img width="1366" alt="Screen Shot 2020-01-28 at 3 19 16 PM" src="https://user-images.githubusercontent.com/5316367/73304994-4b039c00-41e7-11ea-810c-eb05a34296fb.png">

**Comment by hannahkates** [comment]
No longer an issue, closing.
