### ISSUE TITLE
Public Schools data tables showing "NaN"

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#682]
Changes related to #484 are causing the UI to display NaN's.
![image](https://user-images.githubusercontent.com/5316367/79150209-569e4200-7d96-11ea-83ba-cdc56840dbc3.png)

**Comment by godfreyyeung** [comment]
This bug occurs on the Public Schools > Existing Conditions step.
Running into many errors on that step, one of them being this:
![image](https://user-images.githubusercontent.com/3311663/79250493-b0f9da00-7e4c-11ea-8b0c-3ef63d35fd68.png)
