### ISSUE TITLE
On staging, public schools analysis map doesn't update when user clicks "Show School Zones"

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#691]
> In the map, there is an option to check a box to show school zones. This button does not work.
![image](https://user-images.githubusercontent.com/5316367/79881239-f410fb80-83be-11ea-8c23-335064389456.png)

Could be related to #689 and #690

**Comment by allthesignals** [comment]
I can't seem to reproduce this. I think the boundaries might just be slow when loading:

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/ab222934-113f-4da4-8fa8-0514e7b039eb)

**Comment by mshapiro1** [comment]
Works now. Thanks!

**Comment by mshapiro1** [comment]
@allthesignals I'm using staging again, and zones aren't showing up. In previous iterations of CEQR app, this wasn't a problem. Could we look into this further?

**Comment by allthesignals** [comment]
> @allthesignals I'm using staging again, and zones aren't showing up. In previous iterations of CEQR app, this wasn't a problem. Could we look into this further?

@mshapiro1 sure, but I can't seem to reproduce this? Can you share your link?

**Comment by mshapiro1** [comment]
@allthesignals shared my staging project with you on CEQR app ([linked here as well](https://staging.ceqr.app/project/17/public-schools/existing-conditions/study-area)). also pasting an image below

![image](https://user-images.githubusercontent.com/45976493/82485093-e6779000-9aa8-11ea-9b76-39d06256ba85.png)

**Comment by allthesignals** [comment]
@mshapiro1 very weird. you mean the "Show Intermediate SChool Zones", right?

**Comment by allthesignals** [comment]
This must be a browser-specific issue. Can you keep trying and see if you get inconsistent behavior?

**Comment by mshapiro1** [comment]
Yes! Will try again in an hour.

**Comment by mshapiro1** [comment]
@allthesignals tried on MS Edge and Chrome, neither are rendering zones for me
