### ISSUE TITLE
On staging, public schools analysis not updating correctly when toggling between data packages

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#693]
Blocking #484
>No multiplier, existing conditions, or no-action scenario data updates when toggling between data packages.

**Comment by allthesignals** [comment]
Need help verifying this.

Can you take screenshots of which table cells look wrong to you?

I've pushed some changes that might have addressed the issue, but need confirmation because I am seeing data for all the data packages.

**Comment by bfreeds** [comment]
@allthesignals I went through on staging and changed data packages and was able to observe updates to multipliers, existing conditions, and no-action scenario.

**Comment by mshapiro1** [comment]
Works now. Thanks!
