### ISSUE TITLE
On staging, public schools "add Additional Residential Development" not working properly

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#694]
Blocking #484
>In the no-action scenario, the option to add "Additional Residential Development" doesn't work. I can add a development, but it isn't integrated into the analysis numbers.

**Comment by allthesignals** [comment]
Is this actually an issue? When I add an Additional Residential Development on production, I can't tell that it changes anything... which numbers is it supposed to be updating, exactly?

**Comment by mshapiro1** [comment]
@allthesignals It's supposed to modify the "Students Introduced by No Action Residential Development" in the no-action condition, and therefore all the calculations which are based off that number.
